# File này chứa các "bí mật" để chạy ứng dụng trên máy tính của bạn.
# Streamlit sẽ tự động đọc file này khi bạn chạy lệnh "streamlit run app.py".
# Thay thế chuỗi bên dưới bằng API Key thực của bạn từ Google AI Studio.

GEMINI_API_KEY = "dán_api_key_thực_của_bạn_vào_đây"
